name: res_q
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_map: ^4.0.0
  flutter_mapbox_navigation: ^0.1.0
  flutter_speed_dial: ^6.2.0
  flutter_svg: ^2.0.5
  http: ^0.13.6
  latlong2: ^0.8.1
  mapbox_gl: ^0.16.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env