// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuo4LsqHp_rWKwUNH2WVGvHJQ8WWe9Xms',
    appId: '1:20305195461:web:9ef65ff342d10aef119bac',
    messagingSenderId: '20305195461',
    projectId: 'resq-f629a',
    authDomain: 'resq-f629a.firebaseapp.com',
    storageBucket: 'resq-f629a.appspot.com',
    measurementId: 'G-ZXBYVG9HV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAPj8VJcbVzqO9DvZZqL5ZT3PN5MQWFB0',
    appId: '1:20305195461:android:df25cef10b32dc50119bac',
    messagingSenderId: '20305195461',
    projectId: 'resq-f629a',
    storageBucket: 'resq-f629a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBuoWUwmZazxnnzkcho1tSFty0gAwH5HY',
    appId: '1:20305195461:ios:1ae644b5d1cb9743119bac',
    messagingSenderId: '20305195461',
    projectId: 'resq-f629a',
    storageBucket: 'resq-f629a.appspot.com',
    iosClientId: '20305195461-bh2799ar9d96aovq7d8fnnv7k7q1v7m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.resq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBuoWUwmZazxnnzkcho1tSFty0gAwH5HY',
    appId: '1:20305195461:ios:1ae644b5d1cb9743119bac',
    messagingSenderId: '20305195461',
    projectId: 'resq-f629a',
    storageBucket: 'resq-f629a.appspot.com',
    iosClientId: '20305195461-bh2799ar9d96aovq7d8fnnv7k7q1v7m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.resq',
  );
}
